
# SEO settings
title: "格致"
title2: "" # default: ""
description: "Thinking and recording"
keywords: "numerical analysis, CAE, PHP, thinkspace"
url: http://dothinking.github.io/blog # site url
baseurl: "/blog" # apply repo name if use it under gh-pages branch
imageurl: "/blog/_posts/images" # 自定义图片目录

repo: http://github.com/dothinking/blog

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
kramdown:
  input: GFM
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Train"
  job      : "PHD candidate"
  bio      : "正心诚意 格物致知"
  # thumb    : /images/author.jpg
  email    : train8808@gmail.com
  url      : http://dothinking.github.io
  github   : http://github.com/dothinking

gems:
  - bourbon
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 20
paginate_path: ":num"

# navbar pages
# navbar:
#   - slug : about
#     title: About
#   - slug : blog
#     title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
